### ISSUE TITLE
Functions "turnover_allyears" not found

### ISSUE THREAD

**Issue by nnasseri** [NCEAS/codyn#82]
trying to run function: "turnover_allyears" and keep getting errors that it can not be found. Error: 'turnover_allyears' is not an exported object from 'namespace:codyn'

**Comment by mbjones** [comment]
@nnasseri -- Just noticed this issue was filed, but better late than never!  

You should use `turnover()` instead.

The `turnover_allyears()` function is a private function to the package and is not exported,  Its not intended to be used externally, and all of its functionality is exposed through `turnover()`.  So use that please.
