### ISSUE TITLE
Temporal_Diversity_Indices vignette build error

### ISSUE THREAD

**Issue by itcarroll** [NCEAS/codyn#84]
travis-ci build for #83 failed at:

```
$ R CMD build  .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘codyn’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
Quitting from lines 71-76 (Temporal_Diversity_Indices.Rmd) 
Error: processing vignette 'Temporal_Diversity_Indices.Rmd' failed with diagnostics:
Either data span multiple replicates with no replicate.var specified or multiple records within years for some species
Execution halted
```

**Comment by itcarroll** [comment]
The relevant paragraph from the vignette (immediately proceeding the error is)

> Note that if the `replicate.var` column is not specified but the dataset in fact includes replicates, `turnover` will calculate across all species present in a given time point across the dataset. For example, defaulting the `replicate.var` to `NA` while using the entire `collins08` dataset yields total turnover across the unburned and burned locations combined. A warning will be generated to indicate that the metric was calculated across multiple replicates.

The warning has since been changed to an error (in cfbd8fa), so what should the new vignette text be? Should it state instead that `replicate.var` must be specified?

**Comment by mavolio** [comment]
I think what we edit this to say:

Note that if the replicate.var column is not specified but the dataset in
fact includes replicates, turnover will not be calculated and an error
message will appear.

Or something like that.

**Comment by mbjones** [comment]
I think the issue is only about backwards compatibility where the new behavior of throwing an error is incompatible with the old behavior of throwing a warning.  If someone read the vignette that says `A warning will be generated to indicate that the metric was calculated across multiple replicates.`, and then went ahead and used the function anyways in their code (to get that behavior), then that code will break under the new version of codyn.  If there are zero scenarios in which someone would want to use the function that way, then I suppose we could treat the warning as a bug in the original release and fix it here.  But given that we even describe it in the vignette, it seems like expected behavior.

Breaking changes should be avoided if at all possible, but if they must be made, then at a minimum we need to indicate that by making this a major version release (e.g., instead of codyn 1.2.0, this would become codyn 2.0.0).  That version change tells people that they should not expect their old code to work with the new version of the package under all scenarios, and therefore to use caution when upgrading.

So, if you want to fix it despite the compatibility problem, then let's change the vignette to describe the new behavior, and I'll bump the version number to 2.0.0. @laurenmh comments?

**Comment by mavolio** [comment]
Hi @laurenmh,

We are thinking of upgrading codyn to 2.0 because of this incompatibility (our changing a warning to an error for consistency) and the addition of all the new functions. Do you agree?

Meghan

**Comment by itcarroll** [comment]
Leaving ticket open as a reminder to bump version number before release.

**Comment by itcarroll** [comment]
Moving the reminder to #81.
